name: Build and deploy github pages

on:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/deploy-github-page.yml"
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build develop image
      run: >
        docker build ./docs/
        --file ./docs/Containerfile.develop
        --tag docusaurus-develop-image

    - name: Build release image
      run: >
        docker build ./docs/workspace/docusaurus-website/
        --file ./docs/Containerfile.release
        --pull=false
        --tag docusaurus-release-image

    - name: Create build folder for receive build from container
      run: mkdir build
    
    - name: Build from container
      run: >
        docker container run
        --volume ./build/:/workspace/docusaurus-website/build/
        docusaurus-release-image
        npm run build

    - uses: actions/upload-pages-artifact@v3
      with:
        path: build

  # https://github.com/actions/deploy-pages
  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
